name: 更新

on:
  push: 
    paths: 
      - 'trojan.js'
      - 'vless.js'
  workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install -g javascript-obfuscator

      - name: Detect changes for trojan.js
        id: trojan_changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "trojan.js"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Detect changes for vless.js
        id: vless_changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "vless.js"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Obfuscate and zip trojan.js (if updated)
        if: env.changed == 'true' && steps.trojan_changed.outputs.changed == 'true'
        run: |
          javascript-obfuscator trojan.js --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 1 \
            --dead-code-injection true \
            --dead-code-injection-threshold 1 \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 1 \
            --transform-object-keys true \
            --unicode-escape-sequence true
          zip trojan.zip _worker.js

      - name: Obfuscate and zip vless.js (if updated)
        if: env.changed == 'true' && steps.vless_changed.outputs.changed == 'true'
        run: |
          javascript-obfuscator vless.js --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 1 \
            --dead-code-injection true \
            --dead-code-injection-threshold 1 \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 1 \
            --transform-object-keys true \
            --unicode-escape-sequence true
          zip vless.zip _worker.js

      - name: Commit trojan.zip (if updated)
        if: env.changed == 'true' && steps.trojan_changed.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            - trojan.zip
          default_author: github_actions

      - name: Commit vless.zip (if updated)
        if: env.changed == 'true' && steps.vless_changed.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            - vless.zip
          default_author: github_actions